{{- if .Values.envVars }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yapi.fullname" . }}
  labels:
    {{- include "yapi.labels" . | nindent 4 }}
type: Opaque
data: 
{{- range $key, $val := .Values.envVars }}
  {{ $key }}: {{ $val | toString | b64enc | quote }}
{{- end }}
{{- end }}